	{
		SETTING_EMU_CURRENT_SAVE_STATE_SLOT, 
		"Current save state slot", 
		0.0f,
		0.0f,
		YELLOW,
		WHITE,
		"INFO - Set the current savestate slot (can also be configured ingame).",
		LIGHTBLUE,
		0.91f,
		0.09f,
		0.83f,
		&Settings.CurrentSaveStateSlot,
		{0},
		{0},
		0,
		1
	},
	{
		SETTING_SNES9X_AUTO_APPLY_CHEATS,
		"Auto-Apply Cheats",
		0.0f,
		0.0f,
		YELLOW,
		WHITE,
		"INFO - [Auto-Apply Cheats] is set to 'ON'. Automatically apply cheat files if\nit has the same name as the ROM.",
		LIGHTBLUE,
		0.91f,
		0.09f,
		0.83f,
		&Settings.ApplyCheats,
		"INFO - Auto-apply cheats is set to 'On'. Automatically apply cheat files if it\nhas the same name as the ROM.",
		"INFO - Auto-apply cheats is set to 'Off'. Cheat files will not be applied.",
		1,
		1
	},
	{
		SETTING_SNES9X_AUTO_APPLY_PATCH,
		"Auto-Apply IPS/UPS Patch",
		0.0f,
		0.0f,
		YELLOW,
		WHITE,
		"INFO - [Auto-Apply IPS/UPS Patch] is set to 'ON'. Automatically applies similarly\nnamed patch files if they are in the same directory as the ROM.",
		LIGHTBLUE,
		0.91f,
		0.09f,
		0.83f,
		&Settings.NoPatch,
		"INFO - Auto-apply IPS/UPS patch is set to 'Off'. Translation/hack IPS/UPS\npatches will not be applied.",
		"INFO - Auto-apply IPS/UPS patch is set to 'On'. Automatically applies similarly\nnamed patch files if they are in the same directory as the ROM.",
		0,
		1
	},
	{
		SETTING_SNES9X_SRAM_WRITEPROTECT,
		"Savestate SRAM Overwrite Protect",
		0.0f,
		0.0f,
		YELLOW,
		WHITE,
		"INFO - [RAM Overwrite Protect] is set to 'OFF'. Savestates that you\nload will immediately overwrite SRAM.",
		LIGHTBLUE,
		0.91f,
		0.09f,
		0.83f,
		&Settings.SRAMWriteProtect,
		"INFO - [SRAM Overwrite Protect] is set to 'ON'. If you load a savestate\n,it will not overwrite the SRAM. (NOTE: SRAM is not saved)",
		"INFO - [SRAM Overwrite Protect] is set to 'OFF'. Savestates that you\n load will immediately overwrite SRAM.",
		0,
		1
	},
	{
		SETTING_SNES9X_ACCESSORY_AUTODETECTION,
		"Accessory Autodetection",
		0.0f,
		0.0f,
		YELLOW,
		WHITE,
		"INFO - [Accessory Autodetection] is set to 'Confirm'. When detecting a Mouse\nScope/Multitap-compatible game, you are asked if you want to enable it.",
		LIGHTBLUE,
		0.91f,
		0.09f,
		0.83f,
		NULL,
		{0},
		{0},
		0,
		1
	},
	{
		SETTING_SNES9X_ACCESSORY_TYPE,
		"Accessory Type",
		0.0f,
		0.0f,
		YELLOW,
		WHITE,
		"INFO - Accessory Type is set to 'Left analog stick'. The left analog stick\non controller 1 will be used for SuperScope/Mouse games.",
		LIGHTBLUE,
		0.91f,
		0.09f,
		0.83f,
		&Settings.AccessoryType,
		"INFO - Accessory Type is set to 'USB/Bluetooth Mouse'. The mouse will be\nused for SuperScope/Mouse games.",
		"INFO - Accessory Type is set to 'Left analog stick'. The left analog stick\non controller 1 will be used for SuperScope/Mouse games.",
		0,
		1
	},
	{
		SETTING_EMU_DEFAULT_ALL,
		"DEFAULT",
		0.0f,
		0.0f,
		YELLOW,
		GREEN,
		"INFO - Set [all SNES9x settings] back to their 'DEFAULT' values.",
		LIGHTBLUE,
		0.91f,
		0.09f,
		0.83f,
		NULL,
		{0},
		{0},
		0,
		1
	},
	{
		SETTING_SNES9X_FORCE_PAL,
		"Force NTSC ROM to PAL",
		0.0f,
		0.0f,
		YELLOW,
		WHITE,
		"INFO - [Force NTSC ROM to PAL] is set to 'OFF'.",
		LIGHTBLUE,
		0.91f,
		0.09f,
		0.83f,
		&Settings.ForcePAL,
		"INFO - Force PAL is set to 'On' - this will force NTSC games to run at PAL\nfrequencies (50Hz). NOTE: This needs to be set per-game.",
		"INFO - Force PAL is set to 'Off'.",
		0,
		1
	},
	{
		SETTING_SNES9X_FORCE_NTSC,
		"Force PAL ROM to NTSC",
		0.0f,
		0.0f,
		YELLOW,
		WHITE,
		"INFO - [Force PAL ROM to NTSC] is set to 'OFF'.",
		LIGHTBLUE,
		0.91f,
		0.09f,
		0.83f,
		&Settings.ForceNTSC,
		"INFO - Force NTSC is set to 'On' - this will force PAL games to run at\nNTSC frequencies (60Hz). NOTE: This needs to be set per-game.",
		"INFO - Force NTSC is set to 'Off'.",
		0,
		1
	},
	{
		SETTING_SNES9X_PAL_TIMING,
		"PAL Timing",
		0.0f,
		0.0f,
		YELLOW,
		WHITE,
		"INFO - Change PAL timing frequency.\nNOTE: Doesn't need changing from the default value.",
		LIGHTBLUE,
		0.91f,
		0.09f,
		0.83f,
		NULL,
		{0},
		{0},
		0,
		1
	},
	{
		SETTING_EMU_VIDEO_DEFAULT_ALL,
		"DEFAULT",
		0.0f,
		0.0f,
		YELLOW,
		GREEN,
		"INFO - Set [all SNES9x Video settings] back to their 'DEFAULT' values.",
		LIGHTBLUE,
		0.91f,
		0.09f,
		0.83f,
		NULL,
		{0},	
		{0},
		0,
		1
	},
	{
		SETTING_SNES9X_SOUND_INPUT_RATE, 
		"Sound Inputrate", 
		0.0f,
		0.0f,
		YELLOW,
		WHITE,
		"INFO - Set the Sound Inputrate. The default value (31950) is ideal for A/V\nsynchronization.",
		LIGHTBLUE,
		0.91f,
		0.09f,
		0.83f,
		&Settings.SoundInputRate,
		{0},	
		{0},
		31950,
		1
	},
	{
		SETTING_SNES9X_MUTE_SOUND, 
		"Sound Mute", 
		0.0f,
		0.0f,
		YELLOW,
		WHITE,
		"INFO - Mute the sound entirely.",
		LIGHTBLUE,
		0.91f,
		0.09f,
		0.83f,
		&Settings.Throttled,
		{0},
		{0},
		0,
		1
	},
	{
		SETTING_EMU_AUDIO_DEFAULT_ALL,
		"DEFAULT",
		0.0f,
		0.0f,
		YELLOW,
		GREEN,
		"INFO - Set [all SNES9x Audio settings] back to their 'DEFAULT' values.",
		LIGHTBLUE,
		0.91f,
		0.09f,
		0.83f,
		NULL,
		{0},	
		{0},
		0,
		1
	},
